project:
  type: book
  output-dir: docs

book:
  title: "Statistics: An Introduction (PL: Wprowadzenie do Statystyki)"
  author: "Michał Pierzgalski"
  date: "10/24/2025"
  chapters:
    - index.qmd
    - chapter1.qmd
    - rozdzial1.qmd
    - chapter2.qmd
    - rozdzial2.qmd
#    - chapter3.qmd
#    - rozdzial3.qmd
#    - chapter4.qmd
#    - rozdzial4.qmd
    - chapter5.qmd
    - rozdzial5.qmd
    - chapter6.qmd
    - rozdzial6.qmd
    - correg_en.qmd
    - correg_pl.qmd
    - probability_en.qmd
    - probability_pl.qmd
#    - rv_pdf_en.qmd
#    - rv_pdf_pl.qmd
    - inference_en.qmd
    - inference_pl.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    html-math-method: katex
    theme: brite
    number-depth: 2
    mermaid:
      theme: default
      backgroundColor: white
      themeVariables:
        background: white


editor: visual
