# References {.unnumbered}

::: {.callout-caution}
## References
- Blair, G., Coppock, A., & Humphreys, M. (2023). Research design in the social sciences: declaration, diagnosis, and redesign. Princeton University Press. https://book.declaredesign.org/
- Bryman, A., 2016. Social research methods. Oxford University Press.
- Bueno de Mesquita, Ethan and Anthony Fowler. 2021. Thinking Clearly with Data: A Guide to Quantitative Reasoning and Analysis. Princeton University Press.
- Causality for Machine Learning. https://ff13.fastforwardlabs.com/
- Cetinkaya-Rundel, M., Diez, D.M. and Barr, C.D., 2019 (4th ed.). OpenIntro Statistics: an Open-source Textbook: https://www.openintro.org/book/os/
- Claude [Large language model], 2024. https://www.anthropic.com
- Concepts and Computation: An Introduction to Political Methodology. https://pos3713.github.io/notes/
- Hannay, K. (2019). Introduction to statistics and data science. http://khannay.com/StatsBook/
- Ismay, C. and Kim, A.Y., 2019. Statistical Inference via Data Science: A ModernDive into R and the Tidyverse. https://moderndive.com/index.html
- Navarro, D.J. and Foxcroft, D.R. (2019). Learning statistics with Jamovi: a tutorial for psychology students and other beginners. (Version 0.70). DOI: 10.24384/hgc3-7p15
- Remler, D.K. and Van Ryzin, G.G., 2014. Research methods in practice: Strategies for description and causation. Sage Publications.
- Sanchez, G., Marzban, E. (2020) All Models Are Wrong: Concepts of Statistical Learning.
https://allmodelsarewrong.github.io
- Schneider, W. J. (2023). Psycheval: A psychological evaluation toolkit. https://github.com/wjschne/psycheval
- Timbers, T., Campbell, T., & Lee, M. (2022). Data science: A first introduction. Chapman and Hall/CRC. https://datasciencebook.ca/
:::
